[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git |
    \.venv |
    \.tox |
    build |
    dist |
    \.mypy_cache |
    \.pytest_cache
)/
'''  # Exclude specific directories or files